node(){
    stage('Job Name') {
        job: 'First-Maven-Project-Via-DSL_1'
        description: 'First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github'
    }
    stage('git clone') {
        git: 'https://github.com/Srk-771/test-project-1.git'
    }
    stage('pollscm') {
        poll: '* * * * *'
    }
    stage('maven build') {
        sh 'clean package', 'mvn -f pom.xml'
    }
}

